import Category from "../models/category.model";

export const message={
    USERNOTLOGGEDIN:"USER NOT LOGGED IN",
    USERNOTSIGNEDUP:'USER NOT SIGNED UP',
    UNAUTHORIZEDACCESS:'UNAUTHORIZED ACCESS',
    INVALIDCREDENTIALS:'INVALID CREDENTIALS',
    USERSIGNEDUP:'USER SUCESSFULLY SIGNEDUP',
    USERLOGGEDIN:'USER LOGGED IN SUCCESSFULLY',
    USERLOGEDDOUT:'USER LOGGED OUT SUCCESSFULLY',
    USERUPDATED:'USER UPDATED SUCCESSFULLY',
    USERDELETED:'USER DELETED SUCCESFULLY',
    TOKENNOTVERIFIED:'TOKEN NOT VERIFIED',
    INTERNALSERVERORR:'INTERNAL SERVER ERROR',
    USERNOTFOUND:'USER NOT FOUND',
   

    CATEGORYDELETD:"CATEGORY DELETED",
    CATEGORYADDED:"CATEGORY ADDED",
    CATEGORYUPDATED:"CATEGORY UPDATED",
    CATEGORYNOTFOUND:"CATEGORY NOT FOUND"
}